services:
  magang:
    build: ./php
    image: magang:latest
    container_name: magang
    hostname: "magang"
    volumes:
      - ./:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "23306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta

  magang_nginx:
    build: ./nginx
    image: magang_nginx:latest
    container_name: magang_nginx
    hostname: "magang_nginx"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - magang  